MLW 1298
PIH/mirebalais-puppet pull request #170
Opened 2022-01-12 14:55 UTC by jmbabazi

2022-01-12 20:36 UTC, mseaton requested changes

2022-01-12 20:36 UTC, mseaton commented on mirebalais-modules/petl/templates/application-apzu-lowerneno-reports.yml.erb
> +  refreshOpenmrsData: "<%= @petl_cron_time -%>"
What is this cron for? Why do we have both this and startup jobs? Is that intended and do they run the same job?

2022-01-12 20:36 UTC, mseaton commented on mirebalais-modules/petl/templates/application-apzu-upperneno-reports.yml.erb
> +  refreshOpenmrsData: "<%= @petl_cron_time -%>"
What is this cron for?  Why do we have both this and startup jobs?  Is that intended and do they run the same job?

2022-01-12 20:36 UTC, mseaton commented on mirebalais-modules/petl/templates/application-apzu.yml.erb
> +  refreshOpenmrsData: "<%= @petl_cron_time -%>"
Assuming this yml is for the DW server, we don't want to run jobs on a schedule here, right?  We are doing this manually via a cron outside of petl.

2022-01-13 16:34 UTC, jmbabazi commented on mirebalais-modules/petl/templates/application-apzu-upperneno-reports.yml.erb
> +  refreshOpenmrsData: "<%= @petl_cron_time -%>"
I will remove the yaml fiel from the startup job

2022-01-13 17:36 UTC, jmbabazi commented on mirebalais-modules/petl/templates/application-apzu-lowerneno-reports.yml.erb
> +  refreshOpenmrsData: "<%= @petl_cron_time -%>"
fixed

2022-01-13 17:56 UTC, mseaton reviewed
@jmbabazi  see my comments.

2022-01-13 17:56 UTC, mseaton commented on mirebalais-modules/petl/templates/application-apzu-lowerneno-reports.yml.erb
> +  refreshLowerNeno: "<%= @petl_cron_time -%>"
Shouldn't this also have a "refreshUpperNeno" that is set to ""?

2022-01-13 17:56 UTC, mseaton commented on mirebalais-modules/petl/templates/application-apzu-upperneno-reports.yml.erb
> +  refreshUpperNeno: "<%= @petl_cron_time -%>"
Shouldn't this also have a "refreshLowerNeno" that is set to ""?

2022-01-13 17:56 UTC, mseaton commented on mirebalais-modules/petl/templates/application-apzu.yml.erb
> +  refreshOpenmrsData: ""
Shouldn't this be changed to "refreshUpperNeno" that is set to "" and  "refreshLowerNeno" that is set to ""?

2022-01-13 18:25 UTC, jmbabazi commented on mirebalais-modules/petl/templates/application-apzu.yml.erb
> +  refreshOpenmrsData: ""
fixed

2022-01-13 18:27 UTC, jmbabazi commented on mirebalais-modules/petl/templates/application-apzu-lowerneno-reports.yml.erb
> +  refreshLowerNeno: "<%= @petl_cron_time -%>"
Fixed!
If I didn't define it, would it be an issue? My thinking was that since I think have the startup configuration then petl would only search for executeCron.refreshLowerNeno. Thus no need to add executeCron.refreshUpperNeno in this file.

2022-01-13 18:40 UTC, mseaton commented on mirebalais-modules/petl/templates/application-apzu-lowerneno-reports.yml.erb
> +  refreshLowerNeno: "<%= @petl_cron_time -%>"
I'm not sure.

2022-01-13 22:08 UTC, merged