Mlw 1298
PIH/mirebalais-puppet pull request #178
Opened 2022-01-18 18:51 UTC by jmbabazi

2022-01-18 20:13 UTC, cioan requested changes

2022-01-18 20:13 UTC, cioan commented on hieradata/malawi-dw.pih-emr.org.yaml
> +petl_warehouse_db: openmrs_warehouse
@jmbabazi , we are not installing the Pentaho openmrs_warehouse database on the Malawi DW server. Only on Lisungwi and Upper Neno EMR servers.

2022-01-18 20:13 UTC, cioan commented on hieradata/malawi-dw.pih-emr.org.yaml
>  petl_sqlserver_host: 10.160.22.17
we should not be using IP addresses here.

2022-01-18 20:24 UTC, jmbabazi commented on hieradata/malawi-dw.pih-emr.org.yaml
>  petl_sqlserver_host: 10.160.22.17
@cioan, why shouldn't we use IP? 

The IP is for the sql instance and its a vpn IP.

2022-01-18 21:14 UTC, cioan requested changes

2022-01-18 21:14 UTC, cioan commented on hieradata/lisungwi.pih-emr.org.yaml
> +install_petl_warehouse_db: true
It looks like lines 38-40 are duplicates?

2022-01-20 15:01 UTC, cioan approved these changes
Thanks @jmbabazi !

2022-01-20 15:06 UTC, merged